### ISSUE TITLE
버그제보 드립니다. 

### ISSUE THREAD

**Issue by kqjatjr** [JHYOOOOON/ladder-game#3]
<img width="584" alt="image" src="https://github.com/JHYOOOOON/ladder-game/assets/38825685/5cdaed05-fa60-480a-a401-895f8727a6a5">

글자를 입력한뒤에 tab을 누르면 해당 잇풋의 값이 사라지고있습니다. 확인 부탁드립니다.

**Comment by JHYOOOOON** [comment]
안녕하세요~
이 부분은 현재 구글 검색창에서도 동일하게 발생하는 문제로, 크롬 버그로 인식됩니다.
(input창에서 한글 자음 1개 입력 후 Tab키 누를 때 간헐적으로 발생)
<img width="591" alt="image" src="https://github.com/JHYOOOOON/ladder-game/assets/50460114/b368d8dc-3bdb-46f9-90df-d42165a45e17">
최대한 수정하려 해보았으나 keydown 이벤트 핸들러로 확인해봤을 때 value에 바로 공백으로 값이 들어와(ㅁ -> Tab 입력 시, value가 공백으로 잡힘) 근본적인 해결이 어려울 것 같습니다.
제보 감사합니다😄
